"""Add BlendInvite model

Revision ID: c0a39bc39e71
Revises: 4f6709c24153
Create Date: 2026-04-05 18:22:15.802696

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a39bc39e71'
down_revision: Union[str, None] = '4f6709c24153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blend_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('creator_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('creator_name', sa.String(length=80), nullable=False),
    sa.Column('creator_playlist_urls', sa.JSON(), nullable=False),
    sa.Column('creator_include_liked', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('blend_id', sa.String(length=36), nullable=True),
    sa.Column('joiner_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blend_id'], ['blends.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['neon_auth.user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['joiner_id'], ['neon_auth.user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blend_invites_code'), 'blend_invites', ['code'], unique=True)
    op.create_index(op.f('ix_blend_invites_creator_id'), 'blend_invites', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blend_invites_creator_id'), table_name='blend_invites')
    op.drop_index(op.f('ix_blend_invites_code'), table_name='blend_invites')
    op.drop_table('blend_invites')
    # ### end Alembic commands ###
